export { exec, type ExecOptions, type ExecResult } from "./exec.js";

export {
  addPath,
  addPathSync,
  getInput,
  getState,
  setEnv,
  setEnvSync,
  setOutput,
  setOutputSync,
  setState,
  setStateSync,
} from "./env.js";

export {
  addLogMask,
  beginLogGroup,
  endLogGroup,
  logCommand,
  logDebug,
  logError,
  logInfo,
  logNotice,
  logWarning,
  resumeCommands,
  stopCommands,
  type AnnotationOptions,
} from "./log.js";

export {
  getCI,
  getGitHubAction,
  getGitHubActionPath,
  getGitHubActionRepository,
  getGitHubActions,
  getGitHubActor,
  getGitHubActorId,
  getGitHubApiUrl,
  getGitHubBaseRef,
  getGitHubEnv,
  getGitHubEventName,
  getGitHubEventPath,
  getGitHubGraphqlUrl,
  getGitHubHeadRef,
  getGitHubJob,
  getGitHubOutput,
  getGitHubPath,
  getGitHubRef,
  getGitHubRefName,
  getGitHubRefProtected,
  getGitHubRefType,
  getGitHubRepository,
  getGitHubRepositoryId,
  getGitHubRepositoryOwner,
  getGitHubRepositoryOwnerId,
  getGitHubRetentionDays,
  getGitHubRunAttempt,
  getGitHubRunId,
  getGitHubRunNumber,
  getGitHubServerUrl,
  getGitHubSha,
  getGitHubState,
  getGitHubStepSummary,
  getGitHubTriggeringActor,
  getGitHubWorkflow,
  getGitHubWorkflowRef,
  getGitHubWorkflowSha,
  getGitHubWorkspace,
  getRunnerArch,
  getRunnerDebug,
  getRunnerEnvironment,
  getRunnerName,
  getRunnerOs,
  getRunnerTemp,
  getRunnerToolCache,
} from "./vars.js";
